# Generated by Django 4.2.4 on 2023-08-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(default=0)),
                ('emp_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leave_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_leave', models.IntegerField(default=12)),
                ('sick_leave', models.IntegerField(default=8)),
                ('bereavement_leave', models.IntegerField(default=8)),
                ('maternity_leave', models.IntegerField(default=15)),
                ('paternity_leave', models.IntegerField(default=5)),
                ('study_leave', models.IntegerField(default=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('leave_type', models.CharField(max_length=50)),
                ('reason', models.TextField(max_length=100)),
                ('status', models.CharField(max_length=25, null=True)),
                ('days', models.IntegerField(default=0)),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms.employee')),
            ],
        ),
    ]
