# Generated by Django 4.2.4 on 2023-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
